### ISSUE TITLE
Can not open DAO proposal with HMY CLI 

### ISSUE THREAD

**Issue by Stakeridoo** [harmony-one/go-sdk#256]
When I check the DAO proposal I change the space and use
```bash
./hmy governance list-proposal --space=dao-mainnet
 ```
I get  the following output
```bash
QmeyoWEbJ3DSgudcTDW2UQHiU5QqgEAt7GQbYR7vUiedqS | Initial Validator DAO council
 ```

When I try to open the Proposal by
```bash
./hmy governance view-proposal --proposal=QmeyoWEbJ3DSgudcTDW2UQHiU5QqgEAt7GQbYR7vUiedqS
 ```

I get the following Error:
```bash
commit: v417-bc3f026, error: json: cannot unmarshal string into Go struct field ProposalVoteMsgPayload.msg.payload.choice of type int
check hmy cookbook for valid examples or try adding a `--help` flag
  ```

**Comment by LuttyYang** [comment]
It should have been fixed in version 1.2.4

**Comment by Stakeridoo** [comment]
Downloaded 1.2.4 from GitHub. Now after using
```bash
./hmy governance view-proposal --proposal=QmeyoWEbJ3DSgudcTDW2UQHiU5QqgEAt7GQbYR7vUiedqS
 ```
 I get the following error
 ```bash
Warning: Using outdated version. Redownload to upgrade to v417-bc3f026
commit: v1-979e58f, error: json: cannot unmarshal number 2-3-5-8-6 into Go struct field ProposalVoteMsgPayload.msg.payload.choice of type int ```

**Comment by LeoHChen** [comment]
Is it fixed? @Stakeridoo

**Comment by Stakeridoo** [comment]
No still not solved

![error](https://user-images.githubusercontent.com/84278683/122995222-9c4a9780-d3a9-11eb-850c-57c189980d7a.jpg)

**Comment by Stakeridoo** [comment]
I can confirm with latest HMY CLI (version v1-580fa56 (runner@harmony.one 2021-09-13T16:34:01+0000) governance voting is working fine. Will close this Issue
